### ISSUE TITLE
Question: Jax-related issues under the new MacOS 13 (UnexpectedTracerError)? 

### ISSUE THREAD

**Issue by QuinoaGoatee** [YoshitakaMo/localcolabfold#119]
**What is your question?**
Following the instruction, I installed a ColabFold locally. However, when attempting to run it with a short amino acid sequence I get several error messages apparently related to a leaked value. Does anybody know a work-around or is aware of this issue? I'm happy to provide more information as required.

**Computational environment**
 - OS: macOS 13.0.1, MacBook Air M1

Error message below:
[...]
jax._src.errors.UnexpectedTracerError: Encountered an unexpected tracer. A function transformed by JAX had a side effect, allowing for a reference to an intermediate value with shape (2,) and dtype uint32 to escape.
JAX transformations require that functions explicitly return their outputs, and disallow saving intermediate values to global state.
The function being traced when the value leaked was layer at /Users/[username]/Projects/Alphafold/colabfold_batch/colabfold-conda/lib/python3.8/site-packages/alphafold/model/layer_stack.py:128 traced for scan.

[...]

jax._src.errors.UnexpectedTracerError: An UnexpectedTracerError was raised while inside a Haiku transformed function (see error above).
Hint: are you using a JAX transform or JAX control-flow function (jax.vmap/jax.scan/...) inside a Haiku transform? You might want to use the Haiku version of the transform instead (hk.vmap/hk.scan/...).
See https://dm-haiku.readthedocs.io/en/latest/notebooks/transforms.html on why you can't use JAX transforms inside a Haiku module.
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.UnexpectedTracerError

**Comment by MatthewPace98** [comment]
I'm also having this issue on my M1 machine. Trying it on Ubuntu gave me a different JAX error:
`AttributeError: 'Config' object has no attribute 'jax_experimental_name_stack'`

**Comment by QuinoaGoatee** [comment]
I resolved the issue by upgrading jax and the jax library to the current versions.

**Comment by YoshitakaMo** [comment]
Thank you, @QuinoaGoatee . I fixed this issue now!

**Comment by YoshitakaMo** [comment]
@MatthewPace98 The issue may be caused by https://github.com/sokrypton/ColabFold/issues/332 . Please upgrade your dm-haiku to the latest one.

**Comment by YoshitakaMo** [comment]
@MatthewPace98 I've updated the installer and updater to be compatible with the latest JAX/jaxlib and Haiku. See README of this repository and report the feedback. Thank you in advance.

**Comment by MatthewPace98** [comment]
@YoshitakaMo It's running! Thank you for this. I still get these warnings though, not sure if they are significant:
`2022-11-24 11:20:13,871 Remote TPU is not linked into jax; skipping remote TPU.
2022-11-24 11:20:13,871 Unable to initialize backend 'tpu_driver': Could not initialize backend 'tpu_driver'
2022-11-24 11:20:13,871 Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
2022-11-24 11:20:13,871 Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
2022-11-24 11:20:13,871 Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
2022-11-24 11:20:13,871 Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.`
